# Generated by Django 5.1.2 on 2024-11-28 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hnb", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salon",
            name="facebook_acc",
            field=models.CharField(default="", max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="salon",
            name="instagram_acc",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="salon",
            name="share_location",
            field=models.CharField(default="", max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="salon",
            name="whatsapp_link",
            field=models.CharField(default="", max_length=400),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="SalonMaintainer",
            fields=[
                ("maintainer_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=13)),
                ("password", models.CharField(max_length=100)),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="Maintains",
                        to="hnb.salon",
                    ),
                ),
            ],
        ),
    ]
