# Generated by Django 5.1.2 on 2024-11-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hnb", "0002_salon_facebook_acc_salon_instagram_acc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.CharField(default="MALE", max_length=50),
            preserve_default=False,
        ),
    ]
